=== lgarcin/MathQuizKnockout/Exercices/qcm.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="qcm">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="exo" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="theme" minOccurs="1" maxOccurs="unbounded"
								block="restriction">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Nombres complexes" />
										<xs:enumeration value="Géométrie" />
										<xs:enumeration value="Fonctions de plusieurs variables" />
										<xs:enumeration value="Intégration" />
										<xs:enumeration value="Arithmétique" />
										<xs:enumeration value="Fonctions numériques" />
										<xs:enumeration value="Suites numériques" />
										<xs:enumeration value="Algèbre générale" />
										<xs:enumeration value="Equations différentielles" />
										<xs:enumeration value="Polynômes" />
										<xs:enumeration value="Algèbre linéaire" />
										<xs:enumeration value="Algèbre bilinéaire" />
										<xs:enumeration value="Suites et séries de fonctions" />
										<xs:enumeration value="Séries numériques" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="niveau" maxOccurs="1" minOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Première année"></xs:enumeration>
										<xs:enumeration value="Deuxième année"></xs:enumeration>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="enonce" type="xs:string" minOccurs="1"
								maxOccurs="1" />
							<xs:element name="reponse" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="value" type="xs:boolean"
												use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>

						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== lgarcin/MathQuizKnockout/Exercices/Exo056.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Suites et séries de fonctions</theme>
	<niveau>Deuxième année</niveau>
	<enonce>On s'intéresse à la série entière
  $f(x)=\sum_{n\in\dN^*}\frac{x^n}{n}\cos\frac{n\pi}{3}$
  On note $R$ son rayon de convergence.</enonce>
	<reponse value="true">$R=1$.</reponse>
	<reponse value="false">Pour $x\in]-R,R[$,
  $f'(x)=\sum_{n\in\dN}x^n\cos\frac{n\pi}{3}$</reponse>
	<reponse value="false">Pour $x\in]-R,R[$,
	$f(x)=\frac{1}{2}\ln(x^2-x+1)$</reponse>
	<reponse value="false">La suite $\left(\frac{1}{n}\cos\frac{n\pi}{3}\right)_{n\in\dN^*}$ est bornée donc $R\leq1$.</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo020.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Algèbre générale</theme>
	<niveau>Première année</niveau>
	<enonce>A propos des structures.</enonce>
	<reponse value="false">L'ensemble des polynômes de degrés égaux à $n$ ($n\geq1$) pour l'addition usuelle des polynômes est un groupe.</reponse>
	<reponse value="false">L'ensemble des matrices carrés de taille $n$ ($n\geq2$) pour l'addition et la multiplication usuelles des matrices est un corps.</reponse>
	<reponse value="false">L'ensemble des suites convergeant vers $0$ pour la multiplication usuelle des suites est un groupe.</reponse>
	<reponse value="true">Si $G$ est un groupe pour une loi $T$ donnée et $a \in G$, l'ensemble $aG = \{aTx, x \in G\}$ est un groupe pour $T$.</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo001.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Nombres complexes</theme>
	<niveau>Première année</niveau>
	<enonce>Dans les assertions suivantes, lesquelles sont vraies ?</enonce>
	<reponse value="false">$\forall \theta \in \dR, \cos{5\theta} = 16 \cos^{5}{\theta} + 5 \cos{\theta}$</reponse>
	<reponse value="true">$\forall \theta \in \dR, \cos{5\theta} = 16 \cos^{5}{\theta} - 20 \cos^{3}{\theta} + 5 \cos{\theta}$</reponse>
	<reponse value="true">$\cos{\frac{\pi}{10}} = \sqrt{\frac{5+\sqrt{5}}{8}}$</reponse>
	<reponse value="false">$\cos{\frac{\pi}{10}} = \sqrt{\frac{5-\sqrt{5}}{8}}$ car $\cos{\frac{\pi}{10}} \leq \cos{\frac{\pi}{3}}$</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo019.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Algèbre générale</theme>
	<niveau>Première année</niveau>
	<enonce>Soit $E$ un ensemble à $n$ éléments ($n \in \dN^*$). $X,Y,Z$ désignent des parties de $E$.</enonce>
	<reponse value="true">Le nombre de couples $(X, Y)$ tels que $X \cap Y = \emptyset$ est $3^n$.</reponse>
	<reponse value="true">Le nombre de couples $(X, Y)$ tels que $X \cup Y = E$ est $3^n$.</reponse>
	<reponse value="false">Le nombre de couples $(X, Y)$ tels que $(X, Y)$ forment une partition de $E$ est $3^n$.</reponse>
	<reponse value="false">Le nombre de triplets $(X, Y, Z)$ tels que $X \cup Y = Z$ est $3^n$.</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo055.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Suites et séries de fonctions</theme>
	<niveau>Deuxième année</niveau>
	<enonce>On définit une fonction $f$ $2\pi$-périodique en posant pour tout $x\in\dR$ :
	\[f(x)=\sum_{n\in\dN}\frac{\sin^3(nx)}{n!}\]
	On note classiquement $a_n$ et $b_n$ les coefficients réels de la série de Fourier associée à $f$.</enonce>
	<reponse value="true">$f$ est égale à la somme de sa série de Fourier.</reponse>
	<reponse value="false">Pour tout $n\in\dN$, $b_n=\frac{1}{4}\left(\frac{3}{(3n)!}-\frac{1}{n!}\right)$.</reponse>
	<reponse value="true">Pour tout $x\in\dR$,
	 \[f(x)=-\frac{1}{4}e^{\cos3x}\sin(\sin 3x)+\frac{3}{4}e^{\cos x}\sin(\sin x)\]</reponse>
	 <reponse value="true">Pour tout $n\in\dN$, $a_n=0$.</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo037.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Suites et séries de fonctions</theme>
	<theme>Fonctions numériques</theme>
	<enonce>Soit $f$ la fonction définie par $f(x)=\exp\left(-\frac{1}{x^2}\right)$ pour $x\neq0$ et $f(0)=0$.</enonce>
	<reponse value="false">La fonction $f$ est développable en série entière en $0$ car elle est de classe $\cC^\infty$ sur $\dR$.</reponse>
	<reponse value="false">Pour tout $n\in\dN$, il existe un polynôme $P_n$ tel que $f(x)=P_n(x)\exp\left(-\frac{1}{x^2}\right)$ pour tout $x\in\dR$.</reponse>
	<reponse value="true">$f$ est de classe $\cC^\infty$ et pour tout $n\in\dN$, $f^{(n)}(0)=0$.</reponse>
	<reponse value="true">$f$ est de classe $\cC^\infty$ et le rayon de convergence de la série entière $\sum_{n=0}^{+\infty}\frac{f^{(n)}(0)}{n!}x^n$ est infini.</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo052.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Equations différentielles</theme>
	<niveau>Première année</niveau>
	<enonce>Soit $\la\in\dR^*_+$. On considère l'équation différentielle $(E)\;xy'+\la y=\frac{1}{1+x}$ sur $\dR^*_+$.</enonce>
	<reponse value="false">Les solutions de l'équation homogène associée à $(E)$ sont les fonctions $x\mapsto Cx^\la$ où $C\in\dR$.</reponse>
	<reponse value="true">Il existe une unique solution de $(E)$ bornée au voisinage de $0$.</reponse>
	<reponse value="false">Les solutions de $(E)$ sont toutes bornées au voisinage de $0$.</reponse>
	<reponse value="false">Aucune solution de $(E)$ n'est bornée au voisinage de $0$.</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo043.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Arithmétique</theme>
	<niveau>Première année</niveau>
	<enonce>Soient $(a,b)\in\dZ^2$ et $(\cS)$ le système $\syst{x&amp;\equiv a[10]\\x&amp;\equiv b[8]}$ d'inconnue $x\in\dZ$.</enonce>
	<reponse value="false">Le système $(\cS)$ admet toujours une solution.</reponse>
	<reponse value="true">Si $a-b$ est pair, le système admet une infinité de solutions.</reponse>
	<reponse value="false">Si $x$ et $x'$ sont solutions de $(\cS)$, alors $x\equiv x'[80]$.</reponse>
	<reponse value="false">$10a+8b$ est solution de $(\cS)$.</reponse>
</exo>
