=== lgarcin/MathQuizKnockout/Exercices/qcm.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="qcm">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="exo" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="theme" minOccurs="1" maxOccurs="unbounded"
								block="restriction">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Nombres complexes" />
										<xs:enumeration value="Géométrie" />
										<xs:enumeration value="Fonctions de plusieurs variables" />
										<xs:enumeration value="Intégration" />
										<xs:enumeration value="Arithmétique" />
										<xs:enumeration value="Fonctions numériques" />
										<xs:enumeration value="Suites numériques" />
										<xs:enumeration value="Algèbre générale" />
										<xs:enumeration value="Equations différentielles" />
										<xs:enumeration value="Polynômes" />
										<xs:enumeration value="Algèbre linéaire" />
										<xs:enumeration value="Algèbre bilinéaire" />
										<xs:enumeration value="Suites et séries de fonctions" />
										<xs:enumeration value="Séries numériques" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="niveau" maxOccurs="1" minOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Première année"></xs:enumeration>
										<xs:enumeration value="Deuxième année"></xs:enumeration>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="enonce" type="xs:string" minOccurs="1"
								maxOccurs="1" />
							<xs:element name="reponse" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="value" type="xs:boolean"
												use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>

						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== lgarcin/MathQuizKnockout/Exercices/Exo022.xml
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Polynômes</theme>
	<theme>Arithmétique</theme>
	<niveau>Première année</niveau>
	<enonce>Soit $P = \sum_{k=0}^na_k X^k$ avec $a_k \in \mathbb{Z}$ pour $0\leq k\leq n$.</enonce>
	<reponse value="true">Si $(p,q)\in\mathbb{Z}\times\mathbb{Z}^*$ sont premiers entre eux et tels que $\frac{p}{q}$ est racine de $P$ alors $p$ divise $a_0$ et $q$ divise $a_n$.</reponse>
	<reponse value="false">Si $2X^3-X^2-13X+5$ admet une racine rationnelle, c'est nécessairement $1$, $5$, $\frac{1}{2}$ ou $\frac{5}{2}$.</reponse>
	<reponse value="false">$2X^4+X^2+5X+5$ admet une racine rationnelle.</reponse>
	<reponse value="true">Si $a_n=1$, alors toute racine rationnelle de $P$ est nécessairement entière.</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo015.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Equations différentielles</theme>
	<niveau>Première année</niveau>
	<enonce>On cherche à déterminer les fonctions $g$ de classe $\mathcal{C}^1$ sur $\dR^*_+$ et vérifiant
		\[(P)\qquad\forall x &gt; 0, g'(x) = g\left(\frac{1}{x}\right)\]</enonce>
	<reponse value="false">Si $g$ vérifie $(P)$ alors $g$ est de classe $\mathcal{C}^2$ sur $\dR^*_+$ et $x^2g''(x)=g(x)$ pour tout $x\in\dR^*_+$.</reponse>
	<reponse value="true">Si $g$ vérifie $(P)$ et si on pose $h(t)=g(e^t)$ pour $t\in\dR$, alors $h'' - h' + h = 0$.</reponse>
	<reponse value="false">Les fonctions $g : x \mapsto \sqrt{x} \left [A \cos\left(\sqrt3\ln x\right) + B \sin\left(\sqrt3\ln x\right)\right ]$ où $(A, B) \in \dR^2$ vérifient $(P)$.</reponse>
	<reponse value="true">Comme l'équation différentielle $h''-h'+h=0$ est du second ordre et homogène, l'ensemble des solutions forme un espace vectoriel de dimension 2.</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo024.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Polynômes</theme>
	<niveau>Première année</niveau>
	<enonce>Pour $n\in\dN$, on pose $P_n = \sum_{k=0}^n\frac{X^k}{k!}$.</enonce>
	<reponse value="false">$\forall n \in \dN \setminus \{0, 1, 2\}$, $P_n$ possède au moins une racine multiple car $P'_n = P_{n-1}$.</reponse>
	<reponse value="true">$\forall n \in \dN$, $P_n$ est l'unique polynôme vérifiant $P_{n}-P'_{n} = \frac{X^n}{n!}$.</reponse>
	<reponse value="false">$\forall n \in \dN$, $nX^{n+2}-(n+2)X^{n+1}+(n+2)X-n$ admet $1$ comme racine double.</reponse>
	<reponse value="true">Si $m$ est divisible par $n$ alors $\forall a \in \dC, X^m-a^m$ est divisible par $X^n-a^n$.</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo044.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Séries numériques</theme>
	<niveau>Deuxième année</niveau>
	<enonce>Les séries suivantes convergent-elles ?</enonce>
	<reponse value="true">$\sum_{n\geq1}\frac{(-1)^n}{\sqrt n}$</reponse>
	<reponse value="false">$\sum_{n\geq1}\frac{1}{\sqrt n}$</reponse>
	<reponse value="false">$\sum_{n\geq1}\frac{(-1)^n}{\sqrt n}\left(1+\frac{(-1)^{n^2}}{\sqrt n}\right)$</reponse>
	<reponse value="true">$\sum_{n\geq0}(-1)^n\frac{n^2+n+1}{n^3+n^2+n+1}$</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo028.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Algèbre linéaire</theme>
	<niveau>Première année</niveau>
	<enonce>Soient $E$ est un espace vectoriel de dimension finie et $f\in\mathcal{L}(E)$.
		&lt;br/&gt;
		Les conditions suivantes sont équivalentes à $\Ker f \oplus \Im f = E$.</enonce>
	<reponse value="false">$\Ker f \subset \Ker f^2$.</reponse>
	<reponse value="true">$\Im f \subset \Im f^2$.</reponse>
	<reponse value="true">$\Ker f \cap \Im f = \{0\}$.</reponse>
	<reponse value="false">$f$ est un projecteur.</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo031.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Polynômes</theme>
	<theme>Algèbre linéaire</theme>
	<enonce>Soit $n \in \dN$. On se place dans $\dR_n[X]$.</enonce>
	<reponse value="false">$\dim\dR_n[X] = n$.</reponse>
	<reponse value="true">$\forall a \in \dR$, $\cB_a = \left(1, X-a, (X-a)^2, \dots, (X-a)^n\right)$ est une base de $\dR_n[X]$ et d'ailleurs $\cB_0$ en est la base canonique.</reponse>
	<reponse value="false">La matrice de passage de $\cB_a$ à $\cB_0$ est la matrice $\left(a^{k-p} \binom{k}{p}\right)_{1\leq k,p\leq n}$.</reponse>
	<reponse value="false">La matrice de passage de $\cB_0$ à $\cB_a$ est la matrice $\left(a^{k-p} \binom{k}{p}\right)_{1\leq k,p\leq n}$.</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo040.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Algèbre bilinéaire</theme>
	<niveau>Deuxième année</niveau>
	<enonce>Soient $E$ un espace euclidien de dimension $n\geq2$, $a$ un vecteur unitaire de $E$ et $\la$ un réel.
        &lt;br/&gt;
        On définit une forme quadratique $Q$ par $Q(x)=2\langle x,a\rangle^2+\la\|x\|^2$ pour $x\in E$.</enonce>
	<reponse value="true">$Q$ est définie si et seulement si $\la&lt;-2$ ou $\la&gt;0$.</reponse>
	<reponse value="false">$Q$ est positive si et seulement si $\la\geq-2$.</reponse>
	<reponse value="false">$Q$ est non dégénérée si et seulement si $\la\neq0$.</reponse>
	<reponse value="false">Le rang de $Q$ est nécessairement $1$ ou $n-1$.</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo025.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Algèbre linéaire</theme>
	<niveau>Première année</niveau>
	<enonce>Soit $n\in\dN$.</enonce>
	<reponse value="true">La famille $(x\mapsto1,x\mapsto\cos x,\dots x\mapsto\cos nx)$ est libre dans $\dR^\dR$.</reponse>
	<reponse value="false">La famille $(x\mapsto1,x\mapsto\cos x,\dots x\mapsto\cos^nx)$ est libre dans $\dR^\dR$.</reponse>
	<reponse value="true">La famille $(\cosh,\sinh)$ est liée dans $\dR^\dR$.</reponse>
	<reponse value="true">La famille $\left(x\mapsto1, x\mapsto\arctan x, x\mapsto\arctan\frac{1}{x}\right)$ est libre dans $\dR^{\dR^*}$.</reponse>
</exo>
