=== lgarcin/MathQuizKnockout/Exercices/qcm.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="qcm">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="exo" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="theme" minOccurs="1" maxOccurs="unbounded"
								block="restriction">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Nombres complexes" />
										<xs:enumeration value="Géométrie" />
										<xs:enumeration value="Fonctions de plusieurs variables" />
										<xs:enumeration value="Intégration" />
										<xs:enumeration value="Arithmétique" />
										<xs:enumeration value="Fonctions numériques" />
										<xs:enumeration value="Suites numériques" />
										<xs:enumeration value="Algèbre générale" />
										<xs:enumeration value="Equations différentielles" />
										<xs:enumeration value="Polynômes" />
										<xs:enumeration value="Algèbre linéaire" />
										<xs:enumeration value="Algèbre bilinéaire" />
										<xs:enumeration value="Suites et séries de fonctions" />
										<xs:enumeration value="Séries numériques" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="niveau" maxOccurs="1" minOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Première année"></xs:enumeration>
										<xs:enumeration value="Deuxième année"></xs:enumeration>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="enonce" type="xs:string" minOccurs="1"
								maxOccurs="1" />
							<xs:element name="reponse" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="value" type="xs:boolean"
												use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>

						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== lgarcin/MathQuizKnockout/Exercices/Exo057.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Suites numériques</theme>
	<niveau>Première année</niveau>
	<enonce>On définit une suite réelle $(u_n)$ par ses deux premiers $u_0,u_1\in\dR_+$ et par la relation de récurrence
  \[\forall n\geq1,\;u_{n+1}=\frac{u_n^2}{1+u_nu_{n-1}}\]</enonce>
	<reponse value="false">La suite $(u_n)$ est minorée par $1$.</reponse>
	<reponse value="true">Si $(u_n)$ converge, sa limite est nécessairement nulle.</reponse>
	<reponse value="false">Il existe des valeurs de $u_0$ et $u_1$ pour lesquelles $(u_n)$ diverge vers $+\infty$.</reponse>
	<reponse value="true">Il existe $K\in[0,1[$ tel que $u_n=\O(K^{2^n})$</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo014.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Intégration</theme>
	<niveau>Première année</niveau>
	<enonce>On pose $f(x)=\int_0^x3^{-[t]}\,dt$	où $[t]$ note la partie entière du réel $t$.</enonce>
	<reponse value="true">$f$ est définie sur $\dR$.</reponse>
	<reponse value="true">$\forall n \in \dN, f(n) = 3 \frac{1-3^{-n}}{2}$.</reponse>
	<reponse value="false">Pour montrer que $f$ admet une limite en $+\infty$, il est suffisant de montrer que $(f(n))_{n\in\dN}$ converge.</reponse>
	<reponse value="false">$f$ est croissante sur $\dR_+$ et majorée par $\frac{1}{e\ln{3}}$ donc elle admet une limite finie qui est la même que la limite de $(f(n))_{n\in\dN}$, à savoir $\frac{3}{2}$.</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo013.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Intégration</theme>
	<niveau>Première année</niveau>
	<enonce>Si $f$ est une fonction continue sur un segment $[a,b]$, alors</enonce>
	<reponse value="false">$\lim\limits_{n\to+\infty}\frac{1}{n} \sum_{k=1}^nf\left(a+k\frac{b-a}{n}\right) = \int_a^bf(t)\,dt$.</reponse>
	<reponse value="false">$\lim\limits_{n\to+\infty}\frac{1}{n} \sum_{k=0}^{n-1}f\left(a+k\frac{b-a}{n}\right) = \int_a^bf(t)\,dt$.</reponse>
	<reponse value="false">$\sqrt[n]{\prod_{k=1}^n(n+k)} = n e^{\sum_{k=1}^n\ln\left(1+\frac{k}{n}\right)}$.</reponse>
	<reponse value="false">$\sqrt[n]{\prod_{k=1}^n(n+k)} \mathop{\sim}_{+\infty}\frac{n}{e}$.</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo032.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Algèbre générale</theme>
	<theme>Algèbre linéaire</theme>
	<niveau>Première année</niveau>
	<enonce>Soit $f : \cM_n(\dR) \rightarrow \dR$ et vérifiant $\forall (A,B) \in (M_{n}(\dR))^{2}$, $f(AB) = f(A)f(B)$.
    &lt;br/&gt;
    On note $O_n$ la matrice nulle et $I_n$ la matrice identité de $\cM_n(\dR)$.</enonce>
	<reponse value="false">$f$ est un morphisme de groupe pour $M_{n}(\dR)$ muni de la multiplication usuelle des matrices.</reponse>
	<reponse value="false">Nécessairement $f(O_n) = 0$ et $f(I_n) = 1$.</reponse>
	<reponse value="true">S'il existe $p\in \dN$ tel que $A^p=0$ alors $f(A) = 0$.</reponse>
	<reponse value="false">$A\in\cM_n(\dR)$ est inversible si et seulement si $f(A)\neq0$.</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo029.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Algèbre linéaire</theme>
	<niveau>Première année</niveau>
	<enonce>Soient $E$ est un espace vectoriel de dimension $n\geq1$ et $f\in\mathcal{L}(E)$.
		&lt;br/&gt;
		On suppose que $f^n=0$.</enonce>
	<reponse value="false">$\forall x \in E$, $(x, f(x), f^2(x), \dots, f^{n-1}(x))$ est libre.</reponse>
	<reponse value="true">$f$ ne peut être surjectif.</reponse>
	<reponse value="true">Si $f^{n-1}(x)\neq0$, alors $\Ker f=\vect(f^{n-1}(x))$.</reponse>
	<reponse value="false">Si $f^{n-1}(x)\neq0$, alors $\Im f=\vect(x,f(x),f^2(x),\dots,f^{n-1}(x))$.</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo027.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Algèbre linéaire</theme>
	<niveau>Première année</niveau>
	<enonce>Soient $H$ et $K$ deux sous-espaces vectoriels supplémentaires d'un espace vectoriel $E$ de dimension finie.
		&lt;br/&gt;
		Soit $(e_{1}, \dots, e_{k})$ une base de $K$ et $a \in H$.</enonce>
	<reponse value="false">$\dim\left(\vect(e_1+a, \dots, e_k+a)\right) &lt; k$.</reponse>
	<reponse value="true">$\vect(e_1+a, \dots, e_k+a)$ est un supplémentaire de $H$ dans $E$.</reponse>
	<reponse value="false">$\vect(e_1+a, \dots, e_k+a)=K$.</reponse>
	<reponse value="false">On peut montrer ici que tout sous-espace vectoriel d'un espace vectoriel de dimension finie admet au moins deux supplémentaires.</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo002.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Géométrie</theme>
	<theme>Nombres complexes</theme>
	<niveau>Première année</niveau>
	<enonce>Soit le plan rapporté à un repère orthonormé direct $(O, \vec\imath, \vec\jmath)$.
		&lt;br/&gt;
		On considère alors les points $I= (1, 2)$, $M = (2, 3)$ et $M' = (\sqrt{3}, 3+\sqrt{3})$.
		&lt;br/&gt;
		La similitude de centre $I$ qui transforme $M$ en $M'$ est alors</enonce>
	<reponse value="true">de rapport $2$</reponse>
	<reponse value="false">d'angle $\frac{\pi}{4}$</reponse>
	<reponse value="false">de rapport $\frac{1}{2}$</reponse>
	<reponse value="false">d'angle $\frac{\pi}{3}$</reponse>
</exo>

=== lgarcin/MathQuizKnockout/Exercices/Exo007.xml
<?xml version="1.0" encoding="UTF-8"?>
<exo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="qcm.xsd">
	<theme>Fonctions numériques</theme>
	<niveau>Première année</niveau>
	<enonce>On suppose que $f$ est une fonction continue sur $\dR$ admettant une limite finie $\ell$ en $+\infty$ et $a$ est un réel strictement positif.</enonce>
	<reponse value="true">$\forall y \in \dR$, $x \mapsto \int_0^xf(t)\,dt$ est continue sur $[y,y+a]$ et dérivable sur $]y,y+a[$.</reponse>
	<reponse value="true">$\lim_{y\to+\infty}\int_y^{y+a}f(t)\,dt = a\ell$.</reponse>
	<reponse value="false">$\lim_{X\to+\infty}\int_0^X\left(f(t+a)-f(t)\right)\,dt = \int_0^af(t)\,dt + a \ell$.</reponse>
	<reponse value="false">$\lim_{X\to+\infty}\int_0^X\left(\arctan(t+1) - \arctan(t)\right)\,dt = \frac{1}{2} \ln{2} - \frac{\pi}{4}$.</reponse>
</exo>
